policy_type: BCTransformerPolicy
embed_size: 256

transformer_input_size: null
transformer_num_layers: 4
transformer_num_heads: 8
transformer_head_output_size: 32
transformer_mlp_hidden_size: 256
transformer_dropout: 0.1
transformer_max_seq_len: 10

defaults:
    - data_augmentation@color_aug: batch_wise_img_color_jitter_group_aug.yaml
    - data_augmentation@translation_aug: translation_aug.yaml
    - image_encoder: r3m_encoder.yaml
    - language_encoder: mlp_encoder.yaml
    - position_encoding@temporal_position_encoding: sinusoidal_position_encoding.yaml
    - policy_head: mlp_head.yaml
    - proprio_encoder: mlp_encoder.yaml

agg_feat: "AvgPool"
horizon: 10  # please update in libero config too
latent_token: "init_random"