defaults:
  - _self_
  - data: libero
  - policy: core_transformer
  - train: default
  - eval: default
  - sampling: langevin_dyn

# for LIBERO
task_embedding_format: "bert"
task_embedding_one_hot_offset: 1
encode_gripper_cam: True
device: "cuda"